// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.exemple.reservation_rest.stubs;

public interface ReservationIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
