// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.exemple.reservation_rest.stubs;

public interface ReservationListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReservationList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Reservation reservations = 1;</code>
   */
  java.util.List<com.exemple.reservation_rest.stubs.Reservation> 
      getReservationsList();
  /**
   * <code>repeated .Reservation reservations = 1;</code>
   */
  com.exemple.reservation_rest.stubs.Reservation getReservations(int index);
  /**
   * <code>repeated .Reservation reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .Reservation reservations = 1;</code>
   */
  java.util.List<? extends com.exemple.reservation_rest.stubs.ReservationOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .Reservation reservations = 1;</code>
   */
  com.exemple.reservation_rest.stubs.ReservationOrBuilder getReservationsOrBuilder(
      int index);
}
