// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package com.exemple.reservation_rest.stubs;

public interface UpdateReservationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateReservationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>int32 clientId = 2;</code>
   * @return The clientId.
   */
  int getClientId();

  /**
   * <code>int32 chambreId = 3;</code>
   * @return The chambreId.
   */
  int getChambreId();

  /**
   * <code>string dateDebut = 4;</code>
   * @return The dateDebut.
   */
  java.lang.String getDateDebut();
  /**
   * <code>string dateDebut = 4;</code>
   * @return The bytes for dateDebut.
   */
  com.google.protobuf.ByteString
      getDateDebutBytes();

  /**
   * <code>string dateFin = 5;</code>
   * @return The dateFin.
   */
  java.lang.String getDateFin();
  /**
   * <code>string dateFin = 5;</code>
   * @return The bytes for dateFin.
   */
  com.google.protobuf.ByteString
      getDateFinBytes();

  /**
   * <code>string preferences = 6;</code>
   * @return The preferences.
   */
  java.lang.String getPreferences();
  /**
   * <code>string preferences = 6;</code>
   * @return The bytes for preferences.
   */
  com.google.protobuf.ByteString
      getPreferencesBytes();
}
